variable "ai_resource_group_name" {
  description = "Name of the resource group for AI infrastructure"
  type        = string
}

variable "networking_resource_group_name" {
  description = "Name of the resource group for AI Networking infrastructure"
  type        = string
}

variable "location" {
  description = "Azure region"
  type        = string
  default     = "Sweden Central"
}

variable "environment" {
  description = "Environment name"
  type        = string
  default     = "dev"
}

variable "name_prefix" {
  type        = string
  default     = null
  description = <<DESCRIPTION
Optional prefix to be used for naming resources.

This prefix will be applied to all resource names generated by the module. It is useful for ensuring consistent naming conventions across deployments without requiring explicit names for each resource. The prefix should be kept under 10 characters and use only alphanumeric lowercase characters to avoid Azure naming limitations.
DESCRIPTION

  validation {
    condition = var.name_prefix == null || (
      length(var.name_prefix) <= 10 &&
      can(regex("^[a-z0-9]+$", var.name_prefix))
    )
    error_message = "The name_prefix must contain only lowercase alphanumeric characters and be 10 characters or less or remain null."
  }
}

variable "vnet_name" {
  type        = string
  default     = "ai-spoke-vnet-01"
  description = "The name of the AI spoke Virtual Network."
}

variable "vnet_address_space" {
  type        = string
  default     = "10.0.2.0/23"
  description = "The address space for the AI spoke Virtual Network. Must be within smaller than /16 for AI Foundry capability Host injection."
}

variable "existing_zones_resource_group_resource_id" {
  type        = string
  default     = null
  description = "The name of the existing Resource group in the Platform LZ Hub where the Private DNS Zones reside."
}

variable "existing_hub_virtual_network_resource_id" {
  type        = string
  default     = null
  description = "The ID of the existing Hub virtual network."
}

variable "existing_hub_firewall_ip_address" {
  type        = string
  default     = null
  description = "The IP address of the existing Hub firewall."
}

variable "tags" {
  type        = map(string)
  default     = null
  description = "(Optional) Tags of the resource."
}

# ==========================================
# Feature Flags
# ==========================================

variable "enabled_features" {
  type        = set(string)
  default     = ["container_app_environment", "container_registry", "genai_cosmosdb", "genai_keyvault", "genai_storage_account", "genai_app_configuration", "ai_search", "bing_grounding"]
  description = <<DESCRIPTION
Set of features to enable. Valid values:
- apim: Azure API Management
- app_gateway: Azure Application Gateway
- bastion: Azure Bastion
- container_app_environment: Azure Container App Environment
- container_registry: Azure Container Registry for GenAI
- genai_cosmosdb: Azure Cosmos DB for GenAI
- genai_storage_account: Azure Storage Account for GenAI
- genai_keyvault: Azure Key Vault for GenAI
- genai_app_configuration: Azure App Configuration for GenAI
- ai_search: Azure AI Search for knowledge store
- bing_grounding: Bing Grounding service
- build_vm: Build VM
- jump_vm: Jump VM
DESCRIPTION

  validation {
    condition = alltrue([
      for f in var.enabled_features : contains([
        "apim", "app_gateway", "bastion", "container_app_environment",
        "container_registry", "genai_cosmosdb", "genai_storage_account",
        "genai_keyvault", "genai_app_configuration", "ai_search", "bing_grounding",
        "build_vm", "jump_vm"
      ], f)
    ])
    error_message = "Invalid feature name. See variable description for valid values."
  }
}
